#!/usr/bin/env python3
"""
Download all Conan source files needed for air-gapped deployment.

Run this on a machine with internet access, next to download_sources.json
(generated by fetch.py).

Usage:
    python3 download_sources.py                # saves to ./sources next to the JSON file
    python3 download_sources.py /some/dir      # saves to /some/dir
    python3 download_sources.py --data other_sources.json /some/dir
"""

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def _sha256sum(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _download(dest: Path, url: str, file: str, sha256: str = "") -> None:
    target = dest / file
    if target.exists():
        if sha256:
            actual = _sha256sum(target)
            if actual == sha256:
                print(f"  {file}: cached")
                return
            print(f"  {file}: checksum mismatch, re-downloading")
            target.unlink()
        else:
            print(f"  {file}: cached")
            return

    print(f"  Downloading {file} ...")
    subprocess.run(
        ["curl", "--fail", "--silent", "--show-error", "--location", "-o", str(target), url],
        check=True,
    )
    if sha256:
        actual = _sha256sum(target)
        if actual != sha256:
            print(f"ERROR: SHA-256 mismatch for {file}", file=sys.stderr)
            print(f"  expected: {sha256}", file=sys.stderr)
            print(f"  actual:   {actual}", file=sys.stderr)
            target.unlink()
            sys.exit(1)
    print(f"  {file}: OK")


def _clone_and_archive(dest: Path, name: str, version: str, url: str, commit: str) -> None:
    file = f"{name}-{version}.tar.gz"
    target = dest / file
    if target.exists():
        print(f"  {file}: cached")
        return

    print(f"  Cloning {url} at {commit[:8]} ...")
    tmp = Path(tempfile.mkdtemp())
    try:
        subprocess.run(["git", "init", "-q", str(tmp)], check=True)
        subprocess.run(["git", "-C", str(tmp), "remote", "add", "origin", url], check=True)
        subprocess.run(["git", "-C", str(tmp), "fetch", "--depth=1", "origin", commit], check=True)
        with target.open("wb") as f:
            subprocess.run(
                ["git", "-C", str(tmp), "archive",
                 f"--prefix={name}-{version}/", "--format=tar.gz", "FETCH_HEAD"],
                check=True, stdout=f,
            )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    print(f"  {file}: OK")


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("dest", nargs="?", metavar="DIR",
                    help="destination directory (default: ./sources next to the JSON file)")
    p.add_argument("--data", metavar="FILE",
                    help="path to download_sources.json (default: sibling of this script)")
    args = p.parse_args()

    script_dir = Path(__file__).resolve().parent
    data_path = Path(args.data) if args.data else script_dir / "download_sources.json"
    if not data_path.exists():
        sys.exit(f"ERROR: data file not found: {data_path}")

    dest = Path(args.dest) if args.dest else data_path.parent / "sources"
    dest.mkdir(parents=True, exist_ok=True)

    data = json.loads(data_path.read_text())

    print(f"=== Downloading sources to {dest} ===")
    for pkg in data["packages"]:
        print(f"# {pkg['name']}/{pkg['version']}")
        for src in pkg["sources"]:
            if src["type"] == "git":
                _clone_and_archive(dest, pkg["name"], pkg["version"], src["url"], src["commit"])
            else:
                _download(dest, src["url"], src["file"], src.get("sha256", ""))

    print()
    print("=== All sources downloaded ===")
    print("Copy the sources/ directory to the air-gapped machine, then run:")
    print("  python3 scripts/deploy.py --bundle-dir <path/to/bundle>")


if __name__ == "__main__":
    main()
